Added German Translation
pop-os/cosmic-launcher pull request #166
Opened 2024-08-04 21:11 UTC by silverhadch

2025-01-14 18:12 UTC, mmstick requested changes
Missing a translation, and COSMIC is not capitalized

2025-01-16 04:58 UTC, silverhadch commented
> Missing a translation, and COSMIC is not capitalized

Done.

2025-01-16 05:40 UTC, mmstick commented
Still missing translation for the `type-to-search` key

2025-01-16 06:33 UTC, silverhadch commented
> Still missing translation for the `type-to-search` key

Now?

2025-04-08 14:40 UTC, jackpot51 approved these changes

2025-04-08 14:40 UTC, merged