feat: Support `--reverse` for alt-tab
pop-os/cosmic-launcher pull request #183
Opened 2024-09-02 20:52 UTC by bbb651

Also fixes behavior of `alt[-shift]-tab` not triggering the first time when the launcher activates.
This seems to have been done intentionally, but this does not match any existing implementation of window/tab switching I know (e.g. Gnome, KDE, Windows, MacOS, Firefox, Chromium, VSCode, Zed, etc.) and IMO is very bad UX because triggering it once quickly will do nothing windows are sorted by last window focus.

@git-f0x I worked on it some more and I *think* this is all that needs to be done on the `cosmic-launcher` side, but I haven't tried adding the `alt-shift-tab` shortcut yet.

Also, I ended up getting into a bit of a rabbit hole with debugging, to properly test the activation it has to run in cosmic-session, so I ended up symlinking it in-place of my system's `cosmic-launcher`, but then I had to resort to trying to write to a named pipe (which failed but I couldn't figure out why), and displaying it through the UI. Does `cosmic-session` provide a way to view logs for components for the current session, or is there any better way to test?

2024-09-03 14:06 UTC, bbb651 commented
The `cosmic-settings` part is still missing, I'm not sure how to get it to actually use my local version of `cosmic-settings-daemon`, `[patch.'https://github.com/pop-os/cosmic-settings-daemon']` seems to only work for transitive dependencies, `cosmic-settings-config = { path = "../../cosmic-settings-daemon" }` can't find the crate and `cosmic-settings-config = { path = "../../cosmic-settings-daemon", package = "cosmic-settings-daemon" }` renames it to the wrong thing (actually `package = cosmic-settings-config` might work, I haven't tired it yet).

When installing it onto my system (the rest of the packages are the alpha1 version, not git) It currently does not work, I'm not sure why and it's very difficult to debug...

2024-10-08 02:46 UTC, skylerberg commented
I got it using my local version by specifying the exact directory to use by tacking `config` on the end:
 `cosmic-settings-config = { path = "../../cosmic-settings-daemon/config" }`

That should make it easier to debug, so I'll see if I can figure out what the issue is.

2024-10-08 03:05 UTC, skylerberg commented
I have not yet figured out what part of this PR isn't working, but I have figured out why the code intentionally did *not* cycle the first time. The list is not relative to the application you are using. To explain what I mean, suppose you have three applications open, and we will call them Application 1, Application 2, etc.

The list will always display Application 1, Application 2, and Application 3. So if you currently are focused on Application 1 and you quickly strike Alt-Tab and release, nothing will happen. If you are Application 2 and you strike Alt-Tab and release, you will switch to Application 1. Application 1 is always first.

So this change just makes Alt-Tab always select Application 2 first.

What we should really have is a list sorted by most recently focused and have Alt-Tab cycle to the next most recently focused on first press. That also lets you toggle between two tabs.

2024-10-08 03:12 UTC, skylerberg commented
I created the pull request needed for cosmic-settings: https://github.com/pop-os/cosmic-settings/pull/675

Using my cosmic-settings, and your cosmic-settings-daemon, cosmic-comp, and cosmic-launcher is working as expected!

2024-10-08 03:16 UTC, skylerberg requested changes

2024-10-08 03:16 UTC, skylerberg commented on src/app.rs
> +                self.alt_tab = true;
Based on my comment in the conversations section, I think we should switch this back to not cycle when opened for now.
Once we have the applications ordered by most recently focused, we should make the change to cycle on the first use of Alt-Tab.

2024-10-08 07:53 UTC, wiiznokes commented
This sould be covered by https://github.com/pop-os/cosmic-launcher/pull/150 iirc

2025-02-27 18:55 UTC, git-f0x commented
I think this can be closed, since it has been implemented.

2025-02-27 18:57 UTC, closed without merging